### ISSUE TITLE
Build action doesn't properly compare date version parts to integer version parts

### ISSUE THREAD

**Issue by href** [lgiordani/punch#15]
I still have some issues with the build action implemented in #14. Take the following config:

```python
__config_version__ = 1

GLOBALS = {
    'serializer': '{{year}}.{{month}}.{{build}}',
}

FILES = ['setup.py']

VERSION = [
    {
        'name': 'year',
        'type': 'date',
        'fmt': 'YYYY'
    },
    {
        'name': 'month',
        'type': 'date',
        'fmt': 'MM'
    },
    {
        'name': 'build',
        'type': 'integer',
        'start_value': 0
    }
]

VCS = {
    'name': 'git',
    'commit_message': "Release {{ new_version }}",
}

ACTIONS = {
    'build': {
        'type': 'conditional_reset',
        'field': 'build',
        'update_fields': ['year', 'month']
    }
}
```

And the following version file:

```python
year = 2017
month = 6
build = 8
```

When I simulate a build action, the new version is '2017.6.0'. The reason for this is this condition in the action module:

        if new_version == version:
            reset_part.inc()
        else:
            reset_part.reset()

Here new_version and version are considered different, even though they both point at 2017.6.8. The problem is that the new_version points at `'2017', '6', 8`. While the version points at `2017, 6, 8`. That is, the types of the fields are not equal. The new_version contains integers and strings, while the old version contains only integers.

So there should probably be some normalisation.

**Comment by lgiordani** [comment]
I see, actually you mentioned this problem in the former issue, and I thought I solved it. Thanks for the report, I'll work on it asap

**Comment by lgiordani** [comment]
@vovanbo thank you for PR #16! @href can you try that solution while I review the PR?

**Comment by href** [comment]
I'm afraid it doesn't seem to work for me. I'm using Python 3.5 and this is the repository I'm running the command against: https://github.com/OneGov/onegov.applications. Running `punch.py --action build -s` still gives me "2017.6.0".

**Comment by vovanbo** [comment]
@href It will be fine if your `punch_version.py` will contain string representation of `year` and `month`. After first run of fixed punch.py version file will be updated to correct state.

@lgiordani Also, for now if you will change format of `month` to `0M`, then non-fixed punch.py will generate incorrect version file, for example:

```python
year = 2017
month = 06
build = 13
```

Note, that month is incorrect octal number now.

**Comment by href** [comment]
That did it @vovanbo, thank you. I tested it successfully now.

**Comment by lgiordani** [comment]
@vovanbo if I get it correctly, the issue here is that the configuration file contained integers instead of strings, right?

**Comment by lgiordani** [comment]
#22 should fix this problem, @href can you check that as well? @vovanbo solution fixed the issue, but we didn't have any test

**Comment by href** [comment]
I tested the change by @vovanbo before and it solved my issue.

**Comment by vovanbo** [comment]
@lgiordani I think all values stored in version file must be strings. And should be deserialised to proper value after parsing version file. Another approach as I understand from [your comment](https://github.com/lgiordani/punch/pull/17#issuecomment-311589109) at my PR (#17) is store valid Python code in version file. So, may be fix of this issue is not just a stringify of version part values, but store date version parts as Python `datetime` objects. And after `vp.DateVersionPart` should get part of datetime (year, month, day etc.) from `punch_version.py` file.

**Comment by lgiordani** [comment]
@href thanks, but I do not agree with the implementation he proposed, so I tried to come up with another solution. Unfortunately the only test case we have is your configuration, so I started from that and I tried to come up with some code. This is why I asked if you could test my code. I think your version file is wrong because it contains integers instead of strings. Why is that? Did you write the file manually? Or did punch write it?

@vovanbo I'm afraid I didn't understand your point, sorry. Date parts are strings because they are formatted with a specific format that returns strings (`'fmt'` is a valid parameter for `strftime()`). Other parts like `IntegerPart` are integers because, well, the name says integer. Storing date version parts as `datetime` objects is, in my opinion, overkill. The `punch_version.py` is intended to be readable, and `datetime` objects are not that clear if you want to represent only one part of the whole date, I think. If you have a counterexample on this, feel free to post it. Please open another issue, however, as this one is dealing with a specific bug.

Overall, I'm afraid I do no understand what we are trying to solve, sorry. If we can come up with a test or a use case that shows a problem, we can perhaps further discuss the issue. I proposed #22 as a solution for a wrong `punch_version.py` file, which contained integers instead of strings. If this is not the problem, as I thought, please can you help me understand the issue?

**Comment by href** [comment]
@lgiordani Oh sorry, I didn't read your message properly. I actually think I tested #22 before and that's what I was referring to. I thought I mentioned that somewhere, but I must have imagined that.

Anywho, I tested it again to be safe and I can confirm that your approach works. So from my perspective this ticket can be closed as soon as #22 is implemented and released :)

Sorry for the confusion!

Also, since you are asking why my version file contains integers instead of strings. Punch wrote that file from what I can tell and it seems to still do so with your solution. I don't know if this should be the case or not, but the result is fine.

**Comment by vovanbo** [comment]
@lgiordani I just try to find good solution for this issue. Nothing more. In #16 i will try to use native representation of version's parts values. I think `__repr__` is exactly that wanted here, because version part saved in Python file and must be a valid Python code. Therefore i've changed version file writer in PR to something like this ([here](https://github.com/lgiordani/punch/pull/16/files#diff-0d34c842763ffc7d8e5a4ed3dc93a17dR263)):
```python
f.write('{0.name} = {0!r}\n'.format(new_version.parts[i]))
```
So, it's my vision of solution. May be integers must not to be represented as strings.

About readability of `punch_version.py`. I think if users will use more complex behaviour to get some version values, then readability of version file will be lost anyway. But, I agree that this issue is not good place to discuss it.

**Comment by lgiordani** [comment]
@vovanbo thanks! Yeah I know you are trying to help, and it is really appreciated. Sorry if I sounded rude, I just wanted to understand the issue. I think I understand your #22 solution better now. I think you are correctly trying to check if we need to generalise the read/write operation on version parts, and probably `__str__` is what we want (as `__repr__`'s target is a unique internal representation). I will move the discussion to #16 as the use case has been understood and will be solved by one of the PRs (I'll close this as soon as we merge a solution). Thanks

**Comment by lgiordani** [comment]
As I commented in #16 I'm sorry that in the last two months I didn't have time to follow the project, so my understanding of the whole issue is a bit lost. I think #22 solves the issue, but feel free to reopen an issue if something is still wrong. Thanks for the collaboration and sorry again for ignoring the thread for a long time. #22 will be merged in version 1.4.1, I'll release it today.

**Comment by href** [comment]
Thanks @lgiordani. Fwiw, I've been using the PR and it has been working as expected.

**Comment by lgiordani** [comment]
Thank you!
